version: "3.10"

services:
    postgres:
        container_name: "0xterminal-postgres"
        image: "postgres:latest"
        restart: unless-stopped
        volumes:
            - ./.database/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD
        ports:
            - "17288:5432"

    bot:
        container_name: "0xterminal-bot"
        image: "0xterminal-helper-bot"
        restart: "unless-stopped"
        volumes:
            - ./.logs/:/app/.logs
        environment:
            - CONFIG_PATH
