env: "local" # local | dev | prod

telegram:
    token: "paste your telegram bot's token"

postgres:
    host: ""
    port: ""
    user: ""
    name: ""
    password: ""
    sslmode: ""

ocr:
    token: "paste your ocr.space api token"
